spring.application.name=webhook-debugger

server.port=8080

spring.datasource.url=jdbc:postgresql://metro.proxy.rlwy.net:17221/railway
spring.datasource.username=postgres
spring.datasource.password=seioKXfFvkGNSFseKsDlqLfmMehbrskn

spring.data.redis.url=rediss://default:gQAAAAAZgTAAIgcDE0NGRiYzhhNzkxMDc0OTFiOGFhZjlhOWUzY2RjY2ZiYw@caring-polecat-104467.upstash.io:6379

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.websocket.enabled=true

# JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC